<?php

/**
 * Application bootstrap
 *
 * @author Adam Faulkner<adzfaulkner@hotmail.com>
 */

// requires the vendor autoload file generated by composer
require __DIR__ . '/../vendor/autoload.php';

// obtains the pimple container
require __DIR__ . '/config/container.php';
