#!/usr/bin/env php
<?php
use Symfony\Component\Console\Application; 

// include the bootstrap
require_once __DIR__ . '/bootstrap.php'; 

$app = new Application();
$app->add($container['command_product']);
$app->run();
